---

# tasks file for goss/install

- name: goss/runner
  debug:
    msg: "{{ prologue.split('\n') }}"
  when: prologue is defined
  tags:
    - always

- name: Download goss binary
  get_url:
    url:  '{{ goss.url }}'
    dest: '/tmp/{{ goss.url | basename }}'
    mode: '0755'
    checksum: 'sha256:{{ goss.sha256sum }}'
  delegate_to: localhost
  become: False
  run_once: True
  tags:
    - pkg

- name: Install goss
  copy:
    src:   '/tmp/{{ goss.url | basename }}'
    dest:  '{{ goss.path }}'
    mode:  '0755'
    owner: root
    group: root
    validate: '%s --version'
  tags:
    - pkg

- name: Create goss directories
  file:
    state: directory
    path:  '{{ item.path }}'
    mode:  '{{ item.mode }}'
    owner: root
    group: root
  with_items:
    - path: '{{ goss.directories }}'
      mode: '0755'
    - path: /var/run/goss/
      mode: '0777'
  tags:
    - conf
    - dirs

- name: Create custom facts directory
  file:
    path:  /etc/ansible/facts.d
    state: directory
    mode:  '0655'
    owner: root
    group: root
  tags:
    - fact

- name: Generate goss custom facts
  copy:
    dest: /etc/ansible/facts.d/goss.fact
    mode: '0755'
    content: |
      #!/bin/sh -eu

      cat <<EOF
      { "version":     "{{ goss.version }}",
        "path":        "{{ goss.path }}",
        "directories": "{{ goss.directories }}",
        "source":      "{{ goss.url }}"
      }
      EOF
  tags:
    - fact

- name: Generate goss test plan facts
  copy:
    dest: /etc/ansible/facts.d/goss_plans.fact
    mode: '0755'
    content: |
      #!/bin/sh -eu

      goss-prove -l |
        awk '/\*/{ print "\"file\": ""\""$3"\", \"timestamp\":\""$2"\"" }' |
        sed -r -e 's/^/{ /'  -e 's/$/ },/' |
        sed -r -e '1s/^/[ /' -e '$s/},/} ]/'

  tags:
    - fact

- name: Install goss helper scripts
  copy:
    src:  '{{ item | regex_replace("^/", "") }}'
    dest: '{{ item }}'
    mode: '0555'
    owner: root
    group: root
  with_items:
    - /usr/local/bin/goss-prove-runner
    - /usr/local/bin/goss-prove
  tags:
    - goss-prove
    - goss-prove-install

