---

# tasks file for goss

- name: Refresh facts
  setup:
  tags:
    - goss-install

- name: Install goss
  include_tasks: install.yml
  when:
    - goss_install is defined
  tags:
    - goss-install

- name: Run goss tests
  include_tasks: runner.yml
  when:
    - goss_tests is defined
  tags:
    - goss-run
    - goss-test
    - test

