---

# tasks file for goss

- name: Refresh facts
  setup:
  tags:
    - goss-install

- name: Install goss
  include: install.yml
  tags:
    - goss-install

- name: Run goss tests
  include: runner.yml
  when:
    - goss_tests is defined
  tags:
    - goss-run
    - goss-test
    - test

