---

# tasks file for goss/runner

# goss_tests:
#   plans:
#     - name: postgres
#       templates:
#         - /path/to/foo.yaml
#         - /path/to/bar.yaml

- name: Collect goss test plan inventory
  set_fact:
    goss_templates:
      '{{ ([goss_templates | default([]) + item.1]) | sum(start=[]) }}'
  with_items:
    - '{{ goss_tests.iteritems() | list }}'
  tags:
    - always

- name: Create goss test plan directories
  file:
    path:  '{{ item | dirname }}'
    state: directory
    mode:  '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '{{ goss_templates }}'
  tags:
    - test-install

- name: Synchronize goss test plans
  template:
    src:   '{{ item | regex_replace("^/", "") }}.j2'
    dest:  '{{ item }}'
    mode:  '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '{{ goss_templates }}'
  tags:
    - test-install

- name: Run goss test plans
  command:
    goss-prove '{{ item | regex_replace("^/etc/goss/|.ya?ml", "") }}'
  with_items:
    - '{{ goss_templates }}'
  register: goss_output
  until:
    - goss_output.rc == 0
  retries: '{{ goss_retries | default(10) }}'
  delay:   '{{ goss_delay   | default(50) }}'
  changed_when: False
  tags:
    - test

